resources:
  - type: Microsoft.Storage/storageAccounts
    name: myblobstorage
    apiVersion: 2019-06-01
    location: eastus
    properties:
      accessTier: Hot
      supportsHttpsTrafficOnly: true
      enableBlobEncryption: true
      networkAcls:
        defaultAction: Deny
        bypass: AzureServices
        virtualNetworkRules: []
        ipRules: []
        virtualNetworkSubnetId: ""
        azureFilesIdentityBasedAuthentication: false
      minimumTlsVersion: TLS1_2
      allowBlobPublicAccess: true