name: Run Script

on: [pull_request]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28

      - name: execute py script # run main.py
        run: |
          response=$(python complianceCheck.py)
          echo "response<<EOF" >> $GITHUB_ENV
          echo "$response" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        id: check
      - name: Post comment
        uses: KeisukeYamashita/create-comment@v1
        with:
          comment: |
            ${{ env.response }}