name: Run Script

on: [pull_request]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install openai==0.28

      - name: execute py script # run main.py
        run: |
          echo 'RESPONSE<<EOF' >> $GITHUB_ENV
          python complianceCheck.py >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        id: check
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.RESPONSE }}'
            })