on: [pull_request]

name: Compliance Scan

permissions: write-all

jobs:
  codeguard:
    runs-on: ubuntu-latest
    name: Run Byte Brigade Compliance Checker
    steps:
      - name: Check me out!
        uses: actions/checkout@v4
        with:
          repository: byte-bridgade-ai-contest-2023/Compliance-GitHub-Action
          branch: main
          path: ./Compliance-GitHub-Action
      - name: Byte Brigade Compliance Check
        uses: ./Compliance-GitHub-Action
        with:
          number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.ORG_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHATGPT_AUTH_TOKEN: ${{ secrets.API_KEY }}
          API_ENDPOINT: $${{ secrets.API_ENDPOINT }}
          DEPLOYMENT_ID: $${{ secrets.DEPLOYMENT_ID }}
          COMMENT_BY_LINE: true