on: [pull_request]

name: Compliance Scan

permissions: write-all

jobs:
  codeguard:
    runs-on: ubuntu-latest
    name: Run Byte Brigade Compliance Checker
    steps:
      - name: Byte Brigade Compliance Check
        uses: byte-bridgade-ai-contest-2023/Compliance-GitHub-Action@HEAD
        with:
          number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHATGPT_AUTH_TOKEN: ${{ secrets.API_KEY }}
          API_ENDPOINT: $${{ secrets.API_ENDPOINT }}
          DEPLOYMENT_ID: $${{ secrets.DEPLOYMENT_ID }}
          COMMENT_BY_LINE: true